### PR TITLE
feat: add homeworks for second semester by Ternavskii

### PR DESCRIPTION
**Pull request by owl-from-hogvarts**

### CODE REVIEW

**Comment by owl-from-hogvarts** [comment]
Is such structure `pupil-name/homework #.pdf` (`#` means homework number) acceptable?

**Comment by owl-from-hogvarts** [comment]
There is alternative structure possible though: `homework #/name.pdf`

**Review by worthant — CHANGES_REQUESTED** [review]
Sorry, i think this structure is not acceptable(
Our structure should be easily-readable when there would be a lot of homeworks, hence we should divide out "2 semester" distro into "hw1 hw2 .. hw6"
I already divided them and added via pull request to the main branch - see yourself

**Comment by worthant** [comment]
I suppose that it's better to store homeworks not by name, but by their number, because students tend to search homeworks by their number, not by other's name)

**Review by worthant — APPROVED** [review]
LGTM :+1:

**Pull request merged**
